# Generated by Django 6.1 on 2026-09-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_scheduleblock_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
