# Generated by Django 6.1 on 2026-09-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_patient_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='bookings.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bookings.patient'),
        ),
    ]
