# Generated by Django 6.1 on 2026-09-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_appointment_patient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categorie serviciu',
                'verbose_name_plural': 'categorii servicii',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.BooleanField(default=False, help_text='Bifează dacă prețul e minim: se afișează „de la 2500 lei”.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('phone', 'name'), name='unique_patient_per_phone_and_name'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='bookings.servicecategory'),
        ),
    ]
