# Generated by Django 6.1 on 2026-09-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_seed_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Apare pe prima pagină. Alege 3-4 — mai multe încarcă pagina.'),
        ),
    ]
